import { useLocation } from "wouter";
import { ChevronLeft } from "lucide-react";

export default function Terms() {
  const [, setLocation] = useLocation();

  return (
    <div className="min-h-[100dvh] bg-background text-foreground dark">
      <div className="mx-auto max-w-2xl px-6 py-12">
        <button
          onClick={() => setLocation("/")}
          className="mb-8 inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground transition-colors"
        >
          <ChevronLeft className="w-4 h-4" />
          Back to Videofy
        </button>

        <h1 className="text-3xl font-extrabold tracking-tight mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-10">Last updated: August 19, 2026</p>

        <div className="space-y-8 text-sm leading-relaxed text-muted-foreground [&_h2]:text-foreground [&_h2]:font-bold [&_h2]:text-base [&_h2]:mb-2 [&_p]:mb-3 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:mb-3 [&_li]:mb-1">
          <section>
            <h2>1. Acceptance of terms</h2>
            <p>
              By creating an account or using Videofy ("the App"), you agree to these Terms of
              Service. If you do not agree, please do not use the App.
            </p>
          </section>

          <section>
            <h2>2. What Videofy does</h2>
            <p>
              Videofy lets you point your device's camera at a screen, upload a photo, or select a
              frame from a screen recording, and uses AI (Google Gemini) to identify the movie, TV
              show, or clip shown in that image — including title, cast, platform, and other
              metadata where available.
            </p>
          </section>

          <section>
            <h2>3. Accounts</h2>
            <p>
              You need an account to use the App, created via Google Sign-In, phone number, or
              email/password (powered by Firebase Authentication). You're responsible for keeping
              your sign-in credentials secure and for all activity under your account.
            </p>
          </section>

          <section>
            <h2>4. Scan credits and purchases</h2>
            <p>
              New accounts receive a limited number of free scans. Once used up, you can purchase
              additional scan packs (currently 50 scans per pack) through Google Play Billing.
              Every scan attempt uses one credit, whether or not the App successfully identifies
              the content — because identification uses a paid AI service regardless of outcome.
            </p>
            <p>
              Scan packs are one-time purchases, not subscriptions, and do not expire. All payments
              are processed by Google Play; refunds are subject to Google Play's own refund
              policies, not ours.
            </p>
          </section>

          <section>
            <h2>5. Acceptable use</h2>
            <p>You agree not to:</p>
            <ul>
              <li>Use the App for any unlawful purpose or to infringe others' rights;</li>
              <li>Attempt to reverse-engineer, disrupt, or overload the App's services;</li>
              <li>Use automated means to access the App outside its intended interface;</li>
              <li>Resell or redistribute access to the App without our permission.</li>
            </ul>
          </section>

          <section>
            <h2>6. Content and accuracy</h2>
            <p>
              Identification results are generated by AI and provided "as is" — they may be
              incomplete, delayed, or occasionally incorrect. Videofy is a discovery/identification
              tool and does not host, stream, or distribute any copyrighted video content itself.
            </p>
          </section>

          <section>
            <h2>7. Termination</h2>
            <p>
              We may suspend or terminate accounts that violate these terms. You may stop using the
              App and delete your account at any time by contacting us.
            </p>
          </section>

          <section>
            <h2>8. Disclaimer and limitation of liability</h2>
            <p>
              The App is provided without warranties of any kind. To the maximum extent permitted
              by law, we are not liable for indirect, incidental, or consequential damages arising
              from your use of the App.
            </p>
          </section>

          <section>
            <h2>9. Changes to these terms</h2>
            <p>
              We may update these Terms from time to time. Continued use of the App after changes
              take effect constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2>10. Contact</h2>
            <p>
              Questions about these Terms? Reach us at{" "}
              <a href="mailto:support@videofy.co.in" className="text-primary hover:underline">
                support@videofy.co.in
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
